# Should the plugin be enabled?
plugin_enabled: true

# How long can a player run for?
player_max_run_time: 15

# How long should a player have to not sprint in order for their stamina to begin recovering?
player_cooldown_time: 1

# Interval of stamina removal while sprinting (-1 point of hunger per x ms)
stamina_deplete_rate: 10